### ISSUE TITLE
ClientId - Seems to not be getting set

### ISSUE THREAD

**Issue by johnhbarrett** [astro-panda/blazor-powerbi#4]
First off thanks for publishing this repo - nicely written.  

I'm on a blazor wasm myself project and really like the way you've componentized the various aspects of rendering PBI in Blazor.

First off I'm simply running this project with any updates of modification to get it going before adapting slightly for wasm.

Unfortunately I'm seeing this exception the `app.Run();` call is made:

>ArgumentNullException: IDW10106: The 'ClientId' option must be provided.
>Microsoft.Identity.Web.MergedOptionsValidation.Validate(MergedOptions options)

My initial thoughts were I've not set the Azure App Registration up correctly of I 've messed up the appsettings.

I've turned off secrets while I try to work through it doubled checked everything in terms of guids being set correctly.

I'd be interested firstly if you have a success in the 'ClientId' being set?

My appsettings.json:
![image](https://user-images.githubusercontent.com/106383851/176562916-dbc13f51-0830-4fd7-8959-8bd128750819.png)

**Comment by Psypher9** [comment]
Hi and thanks for trying out the repo in addition to leaving a comment. 

So the `ClientId` is still being set by the Microsoft Identity layer here
[AstroPanda.Blazor.PowerBI.Demo/Program.cs#L8-L9](https://github.com/astro-panda/blazor-powerbi/blob/3337ee5b5f0db5848b125b3ee13be58f6caa4eeb/AstroPanda.Blazor.PowerBI.Demo/Program.cs#L8)

If you're trying to set the Azure AD configuration you'll need to make sure you're grabbing the right configuration section.

However, I'm noticing now that the Demo app is targeting an `AzureAd` section. I think I just forgot to change it before pushing last time. I'm willing to bet that if you're trying to run the Demo app it's failing because of lines 8 and 9 in `Program.cs`

**Comment by Psypher9** [comment]
One other thing I'd like to point out is that this project is originally set up to run in Blazor Server mostly because the configuration uses Client secrets and you're access your Power BI workspace as a Service Principal. It's not really recommended to keep those service principal secrets on the client.

However,  we do have plans to break this a part a bit and provide some Web API middleware though so that the components can still run other Blazor WASM and have a quick wire-up with an API that contains the secrets but serves out the embedding tokens needed to show the report.

Please let me know if what I've mentioned is helpful! Good luck!

**Comment by Psypher9** [comment]
By the way, we've been working on a getting started wiki in case you've not seen it yet.

[Getting Started](https://github.com/astro-panda/blazor-powerbi/wiki/Getting-Started---Blazor-Server#before-you-write-any-code-) 

If you find it helpful, I'd appreciate any feedback you've got!
